version: '3.8'

#services:
##  web:
#    build: ./app
#    container_name: app
##    environment:
#      - ENVIRONMENT=production
#    expose:
#      - "5000"

services:
  backend:
    build: ./app
    container_name: app
    env_file:
      - .env
    expose:
      - "5000"
## Volumes ##
    volumes:
      - ./logs:/app/logs
## Gestion Logs Eficiente
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # El archivo no pasará de 10MB
        max-file: "3"   # Solo guardará los últimos 3 archivos

  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
## Gestion Logs Eficiente
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # El archivo no pasará de 10MB
        max-file: "3"   # Solo guardará los últimos 3 archivos
